version: 0.1

phase:
  build:
    commands:
    - sudo su -
    - yum install rpm-build make gcc glibc
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
