version: 0.1

phases:
  build:
    commands:
    - sudo su -
    - yum -y install rpm-build
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
