version: 0.1

phase:
  build:
    commands:
    - sudo su -
    - sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
    - sudo yum install -y apache-maven
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
